image: adnrv/opencv

# Some variables to make your CI DRY
variables:
  FILE: "bin/main.py"

before_script:
  # Execute any scripts here before running your code

stages:
  - build
  - exec_frame
  - exec_source
  - report

build:
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - bin/*
      
# This stage executes our program
exec_frame:
  stage: exec_frame
  script:
    # Note that instead of the makefile you can just call your executable here
    - make exec_frame
  artifacts:
    paths:
      - output/*
      
exec_source:
  stage: exec_source
  script:
    # Note that instead of the makefile you can just call your executable here
    - make exec_source
  artifacts:
    paths:
      - output/*

report:
  image: adnrv/texlive:full
  stage: report
  script:
    - ls
    - cd report
    - latexmk -pdf -pdflatex="pdflatex --shell-escape %O %S" report
    # move the file to the root folder
    - mv report.pdf ../
  artifacts:
    paths:
      - output/*
      - report.pdf
